name: NPM Publish
description: NPM Publish with automatic NPM tag based on prerelease ID
author: 'nasa-gcn'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

runs:
  using: node24
  main: dist/index.js
